import { NextResponse } from "next/server"
import prisma from "@/lib/db"
import { requireSalesPerson, handleAuthError } from "@/lib/auth-helpers"

/**
 * GET /api/sales/my-qr-code
 * Get current sales person's QR code and recruitment stats
 */
export async function GET() {
  try {
    const session = await requireSalesPerson()
    const salesPersonId = session.user.id

    // Get sales person data with recruits count
    const salesPerson = await prisma.salesPerson.findUnique({
      where: { id: salesPersonId },
      include: {
        _count: {
          select: {
            recruits: true, // Count recruited sales persons
          }
        }
      }
    })

    if (!salesPerson) {
      return NextResponse.json(
        { error: "Sales person not found" },
        { status: 404 }
      )
    }

    // Generate QR code URL
    const baseUrl = process.env.NEXTAUTH_URL || 'http://localhost:3000'
    const referralUrl = `${baseUrl}/register?ref=${salesPerson.referralCode}`

    // QR code is stored or generated by referral-utils
    // For now, use a QR code generation service
    const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(referralUrl)}`

    return NextResponse.json({
      referralCode: salesPerson.referralCode,
      qrCodeUrl,
      tier: salesPerson.tier,
      recruitsCount: salesPerson._count.recruits,
    })
  } catch (error) {
    return handleAuthError(error)
  }
}
